# Generated by Django 4.1.1 on 2022-10-12 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complainant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(blank=True, max_length=100, null=True)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('campus', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, null=True)),
                ('events_that_took_place', models.TextField(max_length=200, null=True)),
                ('consequence_suffered', models.TextField(max_length=200, null=True)),
                ('spoken_to_someone', models.TextField(max_length=200, null=True)),
                ('dissatisfied_with_informal_complaint', models.TextField(max_length=200, null=True)),
                ('evidence', models.TextField(max_length=200, null=True)),
                ('recommendation', models.TextField(max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status_of_complaint', models.TextField(max_length=25, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='students_accounts.complainant')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500, null=True)),
                ('action_taken', models.CharField(max_length=500, null=True)),
                ('documents', models.CharField(max_length=50, null=True)),
                ('feedback_status', models.CharField(max_length=50, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='students_accounts.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_not_fair', models.CharField(max_length=500, null=True)),
                ('what_to_happen', models.CharField(max_length=500, null=True)),
                ('documents', models.CharField(max_length=50, null=True)),
                ('feedback', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='students_accounts.feedback')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students_accounts.complainant')),
            ],
        ),
    ]
