# Generated by Django 4.1.1 on 2022-10-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_accounts', '0002_generalissuesupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status_of_complaint',
            field=models.CharField(choices=[('submitted', 'SUBMITTED'), ('pending', 'PENDING'), ('solved', 'SOLVED'), ('appealed', 'APPEALED')], default='submitted', max_length=25, null=True),
        ),
    ]
