# Generated by Django 4.1.1 on 2022-09-22 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students_accounts', '0003_registrationform_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationform',
            name='Confirm_Password',
        ),
        migrations.RemoveField(
            model_name='registrationform',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='registrationform',
            name='Password',
        ),
        migrations.AddField(
            model_name='registrationform',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
