# Generated by Django 4.1.1 on 2022-11-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_accounts', '0003_alter_complaint_status_of_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalissuesupdate',
            name='attached_documents',
            field=models.FileField(default=12, upload_to=None),
            preserve_default=False,
        ),
    ]
