# Generated by Django 4.1.1 on 2022-09-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_accounts', '0004_remove_registrationform_confirm_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='Email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
