# Generated by Django 4.1.1 on 2022-09-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_accounts', '0005_registrationform_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='Confirm_Password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationform',
            name='Password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
