# Generated by Django 4.1.1 on 2022-09-22 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students_accounts', '0006_registrationform_confirm_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
