# Generated by Django 4.1.1 on 2022-10-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_accounts', '0007_alter_registrationform_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintsform',
            name='Complain_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complaintsform',
            name='Consequence_suffered',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='complaintsform',
            name='Dissatisfied_with_Informal_complaint',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='complaintsform',
            name='Events_that_took_Place',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='complaintsform',
            name='Spoken_to_someone',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='complaintsform',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaintsform',
            name='evidence',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='complaintsform',
            name='recommendation',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='complaintsform',
            name='status_of_complaint',
            field=models.TextField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='Campus',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='Confirm_Password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='Course',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='Department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='Email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='First_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='Last_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='Password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='Phone_Number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='RegNo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
