# Generated by Django 4.1.1 on 2022-10-12 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students_accounts', '0008_alter_complaintsform_complain_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Decision_Not_fair', models.CharField(max_length=500, null=True)),
                ('What_To_Happen', models.CharField(max_length=500, null=True)),
                ('Documents', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='registrationform',
            name='user',
        ),
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.CharField(max_length=500, null=True)),
                ('ActionTaken', models.CharField(max_length=500, null=True)),
                ('Documents', models.CharField(max_length=50, null=True)),
                ('feedback_status', models.CharField(max_length=50, null=True)),
                ('AdminId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('AppealId', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='students_accounts.appealform')),
                ('ComplaintId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students_accounts.complaintsform')),
            ],
        ),
    ]
